name: imagesoverwords
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010204'
    - '#fefefc'
    - '#ec7f18'
    - '#fcc52c'
    - '#b03c0d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
